-- IT431 Project 2 — sample schema for the "products" table.
--
-- Paste this into the Supabase SQL Editor, adjust the column list to match
-- your domain (recipes, games, movies, etc.), then run it. You'll need the
-- matching Product type in src/types.ts.

create table if not exists songs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid not null references auth.users(id) on delete cascade,

  -- TODO: replace these placeholders with your real fields (at least 5).
  title        text not null,
  artist       text not null,
  album        text not null,
  key          text not null,
  -- time in mm:ss format
  length       text not null check (length ~ '^[0-5][0-9]:[0-5][0-9]$')
);

-- Row Level Security: the database, not the UI, decides who can do what.
alter table songs enable row level security;

-- Anyone (including anonymous visitors) can read.
create policy "song_select_anyone"
  on songs for select
  using (true);

-- Only signed-in users can insert, and they must stamp their own user_id.
create policy "song_insert_authenticated"
  on songs for insert
  to authenticated
  with check (auth.uid() = user_id);

-- Users can only edit rows they created.
create policy "song_update_owner"
  on songs for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- Users can only delete rows they created.
create policy "song_delete_owner"
  on songs for delete
  to authenticated
  using (auth.uid() = user_id);